name: InvisibleHatPlus
main: InvisibleHatPlus\Main
author: MrDoni98
api: 2.0.0
version: 2.0

commands:
 ihat:
  description: "Получить шапку-невидимку"

permissions:
 ivisiblehat.cmd:
  default: op
  description: "получение шапки"
 ivisiblehat:
  default: op
  description: "использование шапки"
